Remove unused variable
An unused variable will be exposed by a backport of mainline commit
0a5f41767444 ("kbuild: clang: disable unused variable warnings only
when constant").

../kernel/sched/fair.c:6958:7: error: unused variable 'spare_cap' [-Werror,-Wunused-variable]
        long spare_cap, most_spare_cap = 0;
             ^
1 error generated.

(cherry picked from commit 52de4b78d5509b2bd4ec66e8d44a9d8143194ff4)
(cherry picked from commit bb73c77839b50ece4f9e505bc7f1bff3d4d09ee0)

Change-Id: I0edb6ce138869a0ad5b0d0d31740cc13807f3738